### ISSUE TITLE
License for educational purposes

### ISSUE THREAD

**Issue by IrinaMonaEpure** [chindesaurus/BarnesHut-N-Body#3]
Hello @chindesaurus!

 I work in education, and I find your repository to be an excellent resource to base an assignment on for my students. For this reason, I wanted to kindly ask if you would consider adding a [license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) that would allow the modification and distribution of the code for educational purposes. Without one, I am afraid I am not allowed to use it, despite it being public.

If you'd like more information about how your project will be used, I can share my contact information with you. Of course, I will ensure that proper attribution is given to you and your work.

**Comment by chindesaurus** [comment]
Hi @IrinaMonaEpure!

Sure thing - I've added a GPLv3 license. Would love to see some cool N-Body simulations from you and your students!

**Comment by IrinaMonaEpure** [comment]
Thank you so much! I'll make sure to properly attribute your work and I'm also excited to see what my students come up with based on your project during the next semester. If you have any questions or would like to see the outcomes, feel free to reach out at the e-mail in my bio. Thanks again for your support!
